name: Cleanse-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - uses: actions/checkout@v2
    - name: Test
      run: xcodebuild test -project Cleanse.xcodeproj -scheme Cleanse -enableCodeCoverage=YES -destination "platform=iOS Simulator,name=iPhone 8"
    - name: Test CleanseGithubBrowser Sample App
      run: xcodebuild test -project Examples/CleanseGithubBrowser/CleanseGithubBrowser.xcodeproj -scheme CleanseGithubBrowser -destination "platform=iOS Simulator,name=iPhone 8"
    - name: Test CleanseSwiftUI Sample App
      run: xcodebuild -project Examples/CleanseSwiftUIExample/CleanseSwiftUIExample.xcodeproj -scheme adoptme -destination "platform=iOS Simulator,name=iPhone 8"
    - name: Test cleansec
      run: xcodebuild test -workspace cleansec.xcworkspace -scheme cleansec -enableCodeCoverage=YES -destination "platform=macos"
      working-directory: cleansec
